let a = 100;
let b = 3;
let Addition = a+b;
let Subtraction = a-b;
let Multiplication = a*b;
let Division = a/b;
let Modulus = a%b;
let Exponentiation =a**b;
console.log(`sum of a and b: ${Addition}`);
console.log(`Difference between a and b: ${Subtraction}`);
console.log(`Product of  a and b: ${Multiplication}`);
console.log(`${a} divided by ${b}: ${Division}`);
console.log(`Remainder ${Modulus}`);
console.log(`${a} to the power of ${b}: ${Exponentiation}`);
